---
sudo: false
language: python
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - libgmp3-dev
    - ghc-8.2.1
    - cabal-install-head

before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal install idris --dependencies-only
- travis_wait cabal new-install idris
- git clone https://github.com/pheymann/specdris
- cd specdris/
- idris --install specdris.ipkg
- yamllint

install:
- idris --build recursion_schemes.ipkg

script:
- yamllint .travis.yml
- idris --testpkg test.ipkg
